### ISSUE TITLE
Episode 7: key_hook_controller.rb:10:in `viewDidLoad': undefined method

### ISSUE THREAD

**Issue by Sohair63** [FluffyJack/MotionInMotionSourceCode#2]
Whenever i ran the application that have "bubble-wrap" gem, I always face the following error as in your application of Episode 7, I got this as shown in Screen shot.
![screen shot 2014-12-31 at 5 34 59 pm](https://cloud.githubusercontent.com/assets/8349026/5587681/d1112e5a-9113-11e4-89c0-c2d8dc0e052b.png)

**Comment by FluffyJack** [comment]
This part has probably changed a little or you don't have the file. `App.documents_path + '/key_hook'`

This episode is old now, it'll be good as a rough reference but you'll need to double check the current API on the [bubble-wrap website](http://rubymotion.github.io/BubbleWrap/).

**Comment by Sohair63** [comment]
thanks
